// <auto-generated />
namespace Build_School_Project_No_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class modifyMemberDM5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyMemberDM5));
        
        string IMigrationMetadata.Id
        {
            get { return "202109210459188_modifyMemberDM5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
