// <auto-generated />
namespace Build_School_Project_No_4.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class modifyMemberDM3 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifyMemberDM3));
        
        string IMigrationMetadata.Id
        {
            get { return "202109210343209_modifyMemberDM3"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
